### ISSUE TITLE
Update the DCF77 Clock Sync app for the SDK version 0.96 f7

### ISSUE THREAD

**Issue by furippa** [mdaskalov/dcf77-clock-sync#1]
Hello!

Your DCF77 Clock Sync app version `1.0` fails to build with the SDK version `0.96.0-rc f7`. Please update the app in your repository and create a new pull request to the catalog repository with the updated manifest file.

> IMPORTANT: Don’t forget to update the app version and commit version in the manifest file.

[View logs](https://catalog.flipperzero.one/application/65e48b58af926be6face5a32/page)

Flipper Team

**Comment by mdaskalov** [comment]
fixed in #3
