### ISSUE TITLE
Update the DCF77 Clock Sync app for the SDK version 0.97 f7

### ISSUE THREAD

**Issue by furippa** [mdaskalov/dcf77-clock-sync#2]
Hello!

Your DCF77 Clock Sync app version `1.0` fails to build with the SDK version `0.97.0-rc f7`. Please update the app in your repository and create a new pull request to the catalog repository with the updated manifest file.

> IMPORTANT: Don’t forget to update the app version and commit version in the manifest file.

[View logs](https://catalog.flipperzero.one/application/65e48b58af926be6face5a32/page)

Flipper Team

**Comment by mdaskalov** [comment]
fixed in #3

**Comment by RogueMaster** [comment]
> fixed in #3

No, it was not... DateTime needs to be fixed.... could you advise how this app works differently than [this one](https://github.com/arha/flipper-dcf77)?

**Comment by mdaskalov** [comment]
The other app doesn't work for me...

Not sure if the RFID transmission frequency is wrong or at some point it stopped transmitting at all. Have you tested it?

Besides this, I’ve improved the timing so the sync is always successful in 2-3 minutes.

And finally I am sending the signal including carrier frequency using PWM over the GPIO pin, so that with proper antenna the range could be increased greatly.

**Comment by mdaskalov** [comment]
I was able to compile the new version with 0.97.0-rc, what do you mean with DateTime?

**Comment by RogueMaster** [comment]
See [here](https://github.com/RogueMaster/flipperzero-firmware-wPlugins/commit/d60979c4caeaefe8d076d53976ecb1d128bc7c4a) all the changes you will need for DateTime and also formatting :)

**Comment by RogueMaster** [comment]
P.S. All flipper projects use the GPLv3 license

**Comment by mdaskalov** [comment]
ah.. this works for RogueMaster but would be incompatible with the official firmware... 
Thanks for the update!

**Comment by RogueMaster** [comment]
> ah.. this works for RogueMaster but would be incompatible with the official firmware...
> Thanks for the update!

With the changes that I provided it should become compatible with the official dev version

**Comment by mdaskalov** [comment]
should be fixed in #5 :wink:
