### ISSUE TITLE
schematics for external ferrite core antenna?

### ISSUE THREAD

**Issue by asiawatcher** [mdaskalov/dcf77-clock-sync#8]
any schematic on how do we connect the external ferrite core antenna? where to connect the capacitor and resistor ? the capacitor should be how many uF voltage ? Thanks

**Comment by mdaskalov** [comment]
It's difficult to give you exact values as it depends what coil do you have. I've taken a coil from old radio clock and have connected it in series with 220 ohm resistor without capacitor. I've seen this as example in another project. 
The result was not much better then using the RFID antenna.
To make better antenna you can use an online RLC circuit calculator to determine the required values for 77.5 kHz.

**Comment by asiawatcher** [comment]
i see so with the coil you used the range hasnt increased at all? i got many radio clocks high up on the walls and i just need to sync them all without using a ladder !! 

i have this coil https://www.ebay.com/itm/203638784817

as for the resistor does it matter in which polarity you connect it? i mean which color connects to GPIO and which to the antenna?

https://grobotronics.com/resistor-1-2w-carbon-5-330ohm.html

thanks for everything

**Comment by asiawatcher** [comment]
> It's difficult to give you exact values as it depends what coil do you have. I've taken a coil from old radio clock and have connected it in series with 220 ohm resistor without capacitor. I've seen this as example in another project. The result was not much better then using the RFID antenna. To make better antenna you can use an online RLC circuit calculator to determine the required values for 77.5 kHz.

https://www.ebay.com/itm/203638784817

**Comment by asiawatcher** [comment]
i see so with the coil you used the range hasnt increased at all? i got many radio clocks high up on the walls and i just need to sync them all without using a ladder !!

i have this coil https://www.ebay.com/itm/203638784817

as for the resistor does it matter in which polarity you connect it? i mean which color connects to GPIO and which to the antenna?

https://grobotronics.com/resistor-1-2w-carbon-5-330ohm.html

thanks for everything

**Comment by asiawatcher** [comment]
if you could also share the link of the other project i would appreciate it

**Comment by mdaskalov** [comment]
I've seen it [here](https://github.com/luigicalligaris/dcfake77), but also [this repo](https://github.com/harlock974/time-signal) has a nice implementation.
Please keep in mind, that it could be illegal in your country to transmit at this frequency!

Generally speaking using the flipper for this is kind of overkill... Consider using ESP32 or other cheap micro controller for that! Have a look at my [esp32 transmitter](https://github.com/mdaskalov/esp32-dcf77-transmitter)!

To your other questions: resistors does not have polarity! The coil you have is used for receiving, but you can unsolder it and connect it with the receiver to the flipper. Don't expect miracles. I think the maximum range would be less than a meter. Check the second project above where active antenna is used if you want to achieve 10 meters...
